### ISSUE TITLE
Specific proxys return 404 instead of 200

### ISSUE THREAD

**Issue by richardhallett** [datacite/maremma#5]
We are receiving 404s from specific proxys for example:
https://datasets.aida.medtech4health.se/10.23698/aida/brln

This specific proxy uses the hostname in the header to do the appropriate retrieval of results.
Maremma should be sending this.

**Comment by phromo** [comment]
maremma uses Faraday with the excon backend which doesn't seem to automatically add the Host header (which for instance, the default :net_http backend does). Maremma seems to send tho Host header for most HTTP methods (POST, PUT) but not for a GET. The relevant code has been commented out: https://github.com/datacite/maremma/blob/275da4c6cc76b14ead179b5d1dbd95c7eb55ea43/lib/maremma.rb#L145

From client-accessing code, you can override this behaviour in the wait for a fix by:

```
require 'maremma'
TEST_URL = 'https://datasets.aida.medtech4health.se/10.23698/aida/brln'
resp = Maremma.get(TEST_URL, { :headers => {'Host' => URI.parse(TEST_URL.to_s).host }})
puts resp.status # => 200
```

**Comment by richardhallett** [comment]
Your reasoning sounded good and we've integrated the fix now and are rolling it out across the clients that use this.

Many thanks for this contribution, very much appreciated.
